Now we will learn how we can delete using (del) function

In [2]:
import pandas as pd
dataframe = pd.read_csv("Screen Time Data.csv")
dataframe.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [3]:
del dataframe["index"]
dataframe.head()

,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

Now we will learn how we can del using pop

In [4]:
dataframe.pop("Date")
dataframe.head()

,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,Wednesday,187,89,17,41,22,0,0,0,0
1,Thursday,123,78,17,8,9,0,0,0,0
2,Friday,112,52,40,8,4,0,3,0,0
3,Saturday,101,69,9,38,2,0,3,0,0
4,Sunday,56,35,2,43,3,0,1,1,0

Now we will learn how we can del using loc and iloc

In [5]:
dataframe.loc[:,["Total Screen Time ","Social Networking","Other","Yoga"]].head()

   Total Screen Time   Social Networking  Other  Yoga
0                 187                 89     41     0
1                 123                 78      8     0
2                 112                 52      8     0
3                 101                 69     38     0
4                  56                 35     43     0

In [6]:
dataframe.iloc[:,[1,3]].head()

   Total Screen Time   Reading and Reference
0                 187                     17
1                 123                     17
2                 112                     40
3                 101                      9
4                  56                      2

Now we will learn how we can del using drop

In [7]:
import pandas as pd
dataframe = pd.read_csv("Screen Time Data.csv")
dataframe.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [8]:
dataframe.drop("Total Screen Time ",axis=1,inplace=True)
dataframe.head()

,index,Date,Week Day,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,35,2,43,3,0,1,1,0

In [9]:
dataframe.drop(columns=["Date","Yoga"],inplace=True)
dataframe.head()

,index,Week Day,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity
0,0,Wednesday,89,17,41,22,0,0,0
1,1,Thursday,78,17,8,9,0,0,0
2,2,Friday,52,40,8,4,0,3,0
3,3,Saturday,69,9,38,2,0,3,0
4,4,Sunday,35,2,43,3,0,1,1

In machine learning we separet indipendent and dependend data from sourch by x and y in formal way

In [10]:
import pandas as pd
dataframe = pd.read_csv("Screen Time Data.csv")
dataframe.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [11]:
x = dataframe.drop("Other",axis=1)
x.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,3,0,1,1,0

In [12]:
y = dataframe["Other"]
y.head()

0    41
1     8
2     8
3    38
4    43
Name: Other, dtype: int64

Now we will learn how can delete row

In [16]:
dataframe.drop([0,1],axis=0).head() # Axis = 0 means it indicate the row and axis =1 means it indicates column

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0
5,5,04/22/19,Monday,189,68,0,9,3,4,0,0,0
6,6,04/23/19,Tuesday,158,56,18,41,12,15,0,0,0