In [3]:
import pandas as pd
dataframe = pd.read_excel('Workbook1.xlsx')
dataframe

   age  income
0    1   10000
1    2   20000
2    3   30000
3    4   40000
4    5   50000
5    6   60000
6    7   70000

In [5]:
dataframe2 = pd.read_excel('Workbook1.xlsx',sheet_name=['Sheet2'])
dataframe2

{'Sheet2':    sl  marks
 0   1     23
 1   2     54
 2   3      7
 3   4     45
 4   5     67
 5   6     56}

In [6]:
dataframe3 = pd.read_csv('Workbook1.csv')
dataframe3

   age  income
0    1   10000
1    2   20000
2    3   30000
3    4   40000
4    5   50000
5    6   60000
6    7   70000

In [ ]:

dataframe3 = pd.read_csv("C:\\Users\\rimon\\Pandas\\Workbook1.csv")
# we have to write path by double slash

dataframe3

   age  income
0    1   10000
1    2   20000
2    3   30000
3    4   40000
4    5   50000
5    6   60000
6    7   70000